name: 'Macosx installation commands'

runs:
  using: "composite"
  steps:
    - name: Install MPI, OpenMP
      run: |
        brew install open-mpi
        brew install libomp
        mkdir bin
        ln -s gfortran-8 bin/gfortran
        echo "PATH=$(pwd)/bin:${PATH}" >> $GITHUB_ENV
        echo "MPI_OPTS='--oversubscribe'" >> $GITHUB_ENV
      shell: bash
