name: 'Macosx installation commands'

runs:
  using: "composite"
  steps:
    - name: Install MPI, OpenMP
      run: |
        brew install open-mpi
        brew install libomp
        mkdir bin
        which gfortran-8
        #install_folder=$(dirname "$(which gfortran)")
        ln -s /usr/local/bin/gfortran-8 /usr/local/bin/gfortran
        #echo "PATH=$(pwd)/bin:${PATH}" >> $GITHUB_ENV
        echo "MPI_OPTS='--oversubscribe'" >> $GITHUB_ENV
      shell: bash
