# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Pyccel tests

on:
  push:
  pull_request:
    branches: [ master ]

jobs:

  MacOSX:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        uses: ./.github/actions/macos_install
      - name: Install python dependencies
        uses: ./.github/actions/pip_installation
      - name: Test with pytest
        uses: ./.github/actions/pytest_run
